baseurl = "https://hyas.netlify.app/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10

# Source: https://gohugo.io/getting-started/configuration/#timeout
timeout = 60000

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = [ "HTML", "RSS", "Sitemap" ]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats.Sitemap]
  mediatype = "application/xml"
  baseName = "sitemap"
  rel  = "sitemap"
  isPlainText = false
  isHTML = false
  noUgly = true
  permalinkable = false

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  plugin = "plugins"
  theme = "themes"
  showcase = "showcase"

[permalinks]
  blog = "/blog/:title/"
  plugins = "/plugins/:slug/"
  themes = "/themes/:title/"
  showcase = "/showcase/:title/"

[minify]
  disableXML = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.xml]
      keepWhitespace = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "tags"
    weight = 80
    [[related.indices]]
    name = "date"
    weight = 10
