# Meta Data for SEO

## Homepage
title = "Hyas"
titleSeparator = "-"
titleAddition = "Build websites faster"
description = "Hyas is a Hugo-powered Jamstack framework for building production-ready websites."

## Open Graph
images = ["images/hyas-schema-image.png"]
ogLocale = "en_US"
titleHome = "Hugo-powered Jamstack framework"

## Twitter Cards
twitterSite = "@gethyas"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Hyas"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "images/hyas-schema-logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "images/hyas-schema-image.png"
schemaImageWidth = 2048
schemaImageHeight = 1024
schemaTwitter = "https://twitter.com/gethyas"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/hyas"

# Feed
copyRight = "Copyright (c) 2019-present Hyas"

# Footer
# footer = "&copy; 2022 Hyas — <a href=\"https://www.netlify.com/\" target=\"_blank\">Deploys by Netlify</a>"
footer = "&copy; 2022 Hyas"
sponsor = "Deploys by Netlify"

# Alert
alert = true
alertDismissable = true
# alertText = 'From Modern Hugo Starter to Hugo-powered Jamstack framework. <a class="text-link active stretched-link" href="/blog/how-hyas-evolved-into-a-framework/">Explore how Hyas evolved</a>!'
alertText = '⚠️ This site is still in beta. The documentation is not yet complete.'

# Images

## defaultImage
defaultImage = "spencer-davis-ilQmlVIMN4c-unsplash.jpg" # put in `./assets/images/`

## imaging
[imaging]
  anchor = 'Smart'
  bgColor = '#fff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'Lanczos'

## lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  # maxSize = "1920x"
  maxSize = "1366x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid rounded-3"
  # alt = ""
  noscript = true

  errorHandler = "warning"

# Sections
[sections]
  # mainSections = ["blog", "docs"]
  sectionNav = ["docs", "plugins", "themes", "sorts", "showcase", "types", "features"]
