name: Hyas CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        os-version: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 19.x]

    steps:
    - name: Check out project
      uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Set pnpm config 1/2
      run: pnpm config set '@ventizo:registry' "https://npm.pkg.github.com"

    - name: Set pnpm config 2/2
      run: pnpm config set '//npm.pkg.github.com/:_authToken' "${VENTIZO_AUTH_TOKEN}"
      env:
        VENTIZO_AUTH_TOKEN: ${{secrets.VENTIZO_AUTH_TOKEN}}

    - name: Install dependencies
      run: pnpm install

    - name: Run test script
      run: pnpm test

    - name: Build production website
      run: pnpm build